# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.java.home=C:/Users/msoli/.gradle/jdks/eclipse_adoptium-25-amd64-windows.2

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Mod Properties
version=1.0.0
group=dev.patitow.industrymade

# Dependencies
fabric_api_version=0.155.3+26.1.2
